In [26]:
import numpy as np
a1=[0,1,2,3]
a2=np.array([[0,1,2,3],[4,5,6,7]])
for i,j in np.nditer([a1,a2]):
    print(i," ",j)
 

0   0
1   1
2   2
3   3
0   4
1   5
2   6
3   7


In [25]:
sum=0
pro=1
a1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(a1):
    sum+=i
    pro*=i
print(sum)
print(pro)

78
479001600


In [27]:
a3=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(a3[1::2,1::2])

[[ 5  7]
 [13 15]]


In [31]:
a4=np.arange(12).reshape(3,4)

In [32]:
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
a4[:,[0,1]]=a4[:,[1,0]]
print(a4)

[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


In [41]:
# Perlogo
x=np.array([[20,20,20],[30,30,30],[50,50,50]])
v=np.array([20,30,50])
result=x//v[:,None]
print(result)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [59]:
# There is an array of scores of 5 Batsmen in 4 T20 Matches. Which is given below.
# Scores= [[31, 12, 19, 53],
#                [67, 48, 95, 83],
#                [59, 67, 13, 59],
#                [62, 29, 99, 88],
#                [87, 91, 69, 76]]
# 1. Find the maximum score in T_20-3 and print it (use only the numpy module)
# 2. Find the minimum score of YUVRAJ and print it (use only the numpy module)
# 3. Add an extra column with the sum of all 4 T20 Matches’ scores of each batsman in the array created and print it. (use only the numpy module)   
Scores=np.array([[31, 12, 19, 53],
         [67, 48, 95, 83],
         [59, 67, 13, 59],
         [62, 29, 99, 88],
         [87, 91, 69, 76]])
max_score=np.max(Scores[:,2])
print(max_score)
min_score=np.min(Scores[2,None])
print(min_score)
for i in np.nditer(Scores[:,None]):
    j=0
    total=np.array[i]
print(total)

99
13


TypeError: 'builtin_function_or_method' object is not subscriptable